### ISSUE TITLE
打开导入的书籍闪退以及一点个人想法

### ISSUE THREAD

**Issue by amokiel** [octopusring/reamicro-binary#1]
冒昧打扰，用的是10.1的最新版本，本地模式下导入了一本3M大小的epub书籍，打开书籍时直接闪退。不过也试了下最早期的版本没有这个问题，可以正常打开，不过最早期版本目录选择章节功能很不灵，早期版本的页面要比最新版本好看很多，挺美观方便的。其中，我也尝试了好多最近几个月的版本，基本上都是打开书籍就闪退，不过早期版本好像都是正常的。希望可以能够在设置里隐藏社区功能，个人之所以用本地阅读，其实就是因为不喜欢阅读还搞什么社交元素，要不然肯定就用微信读书了。微信读书正是因为社交功能等一系列与阅读无关的东西加的太多，所以被我放弃使用。个人希望能够向静读天下看齐，静读天下各方面挺好的，就是页面不太美观。本地阅读器完全可以做成静读天下专业版那样的买断模式，那样一定支持，价格贵点其实也没关系。微信读书的页面交互其实挺好的，本来想着如果有开发者做个类似的美观简洁的本地版就好了。后来发现了厚墨，一直用了两三年，现在还用着1.3版本。由于厚墨1.3版本书源可用的越来越少，于是还搭配着轻墨使用。厚墨1.3虽然支持本地书籍，txt书籍体验很不错，不过epub支持还是不太好的，其它格式体验也不是很完美。所以目前同时用着厚墨，轻墨，静读天下专业版，起点。其实如果真想要做书籍阅读社区的话，完全可以做个专门的APP，这方面似乎还没有体验很好的社区，如果真有个这样的社区，我应该也会去用的。所以说，我认为完全没必要把所有功能都做到同一个APP里面，大而全不是什么好事，这样会很臃肿累赘，其实单独做一个阅读分享社区APP应该是一个更好的选择。以上仅是个人的一些浅薄见解，如有冒犯，还请见谅。开发者辛苦了，感谢您的辛苦工作！

**Comment by Liloupar** [comment]
客气了

**Comment by amokiel** [comment]
> 客气了

我的想法是完全可以向纯纯写作那样做好APP本身，也就是做好本地阅读的体验，那样再搞账号系统绑定，就可以定高点价格。产品质量好，总会有人认可的。
